### PR TITLE
Big data

### PR DESCRIPTION
**Pull request by envomp**
Changes made to deploy ofbiz easily with docker and some core changes not visible to others

### CODE REVIEW

**Review by kilpkonn — CHANGES_REQUESTED** [review]
- Can we avoid doing `./gradlew cleanAll loadAll` between every docker restart / build and only do it once when the container is created?
- Can we have xml-s etc volume mounted into container so no restart is required for small changes?
- I think some guidelines should be specified for camel endpoints (How we name api, what classes do what etc.)  

Rest of the changes look good to me.  
 _(Can't comment about NoSQL so someone has to review that)_

**Comment by envomp** [comment]
Added deploy-dev.sh file.
CI / CD in master will still use deploy.sh file.

**Review by kilpkonn — APPROVED** [review]
I'd still add some guide how to name / structure stuff. Otherwise looks good!

**Comment by martinrebane** [comment]
Hi @envomp! Can you briefly comment on what are the changes in "some core changes not visible to others"?

**Comment by envomp** [comment]
Hello, @martinrebane! We extended the existing delegator and the components it's currently using. GenericDelegators functionality has not changed but instead, we're making a noSQL extension to delegator factory. The only thing that's really visible for them is the docker orchestration, so they can make a connection to containers straight up if they want to check how entity's were created. (DB tools will start by running the .sh file)

**Pull request merged**
